"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
BARD_API_KEY =config("BARD_API_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
import corsheaders

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'base',
    'rest_framework',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'base.middleware.DemoMiddleWare',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# PRIVAETE_KEY= "\nhTZ7IlAaR8W5b5yfZBX+UnzQO1LVxmsmJFwwY+vrrhXTYqd6g+yTWv1gUqN5360N\nPLeZp7WNtkBukqelTWHfQRGdQ0yoGCjFgqTW7Yt/M6f8BfEnL67eEmJ8D2Fq0+7U\noNSJuSogBy9YjDTYgP7l4G9BLq9U7vE4bdfStrDoOWHfBdCh2WPxhaFIAITJDf+0\nbPqUOYD/l6cNFhRlWlIN7TKD+qOy+Q2J6cvxLentJaY00RgFw0nJ1aewsKd9dPF4\noTke9u/cjBnGhKCPHL2PKGZCsyEJSAn6tm5C7YU07XVrfwvsiMsXcGG3tjvbpywj\n70NjftjpAgMBAAECggEAARZUDvq8aZ3vM5NndroLgONHyJkz8HRRmumJoxqp/p3i\nip3K4dDRPNIbfOIstq8S5yE8ENBLCKo25PaNejgj9UX+hLu9v6EKnaXt1ihyutGd\n9cVcJwRGgmVBhetat/nEds/5YuEKkkvLw/Mfg1CFUWcVgcf1hIjuFvCp704jQVAn\n8yNAQTFWJKGsToTxAnccxZA7TyY+eRPGP5JoGM5LIC2lGiKpX6PuCUB0OdkXkXCz\nQIK2QGVAMHlgTww4OS+/WvTLgZct+mvGkaVwoxkKysOXwN0V3j0ls8H+X5cUrEc+\nfq89XjHfFK6Ihblc6GG31TslZHF1cQAuamDY+ywC5wKBgQDB7L3vr+MFrAVDXt3+\nHL4Js4WsaMgTp+otie4oN64O6GgJDSOj0YoOzWGL758qTGxVYHPXtZTa/6MnKcSf\nDLRs6cOmAs68bBFsj0a2+5MpZyGIDNX/ddBcOBhG0Wc+4zcCHJTsbPIwPXZOU4OB\nSFnqS7RmgIytWw3zLSucUwocJwKBgQC6JIHcEzDaeztP488sd7wmkiRETxvNbFyO\nxb1Hmn+8di09zxBHeyKc4F0H22vSBKknR4fCh8uzEjS0Bciz20B3bT8o+gKm5pby\nAr+qANOJ8puQRgyUl3W40yEwZQXWc/FGcoSvMA907OJKLDxvqsBZ4PQbS0Wd7bAn\nkh1ZFRC8bwKBgB+QU/3uR+pFbHnhuApDTV8w3CIKz/37B6+v0pazMV51z3EhtVpV\nob31CdqH/wUYeU2QLGrAwGDA2SJntvwYSkmr5s9fh5y9jjx4OY9Q9Uv44ElPpYk1\n+Nr5umHUdZST0QFD+61bsjPN3TK0fyQMza3H8q34YG1a87NP99gy3+NjAoGBAIDm\nXQLQS0lQgt8syz9o3uL62qBvA7q6KlI3/n4CMCiK0YN2yzgkvfBSsjmJqd1ymsx3\njTyZmuazWcm8I6Lg1oCdJ1qx3npDPg3y91S7Y8GoPi+nQnj3dW76zYXcvzElctQs\n41MJffqjO4TPoz5UyQS0cXYhJuFZQl30odwZaVCDAoGBALvKDUnw2lE3eBjyWUJi\ne1ndZ+fPfUjAbx4KF/SCskOffbLBrZAPXFP2eRzdcjjd50+z34UL8w6dQuSqIgHO\nPUBqWzmFCozA65dBvMHGckjIrA+6RqZwr9f0qpB/z7yW3xJAvlRPmuz1sVf2okAW\nu7OU89Lt3qv+IHj0awaBh0ik\n-----END PRIVATE KEY-----\n",
KEY = "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCNAamp3TJDpa9i"
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_ALLOW_ALL_ORIGINS = False
import os
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
